# -*- coding: utf-8 -*-
# Generated by system.
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from queue.models import Queue


def create_queue(apps, schema_editor):
    Queue.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_queue)
    ]
