# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_queue_singleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
