# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfmodel',
            name='permission_type',
            field=models.IntegerField(choices=[(0, 'Free use'), (1, 'Single user'), (2, 'Team')], default=0),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='permitted_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
        migrations.AddField(
            model_name='tfmodel',
            name='permitted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ExtendedUser'),
        ),
    ]
