# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0002_auto_20160918_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfmodel',
            name='external_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
