# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf', '0003_auto_20160918_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=8)),
                ('results', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
